- name: Create Docroot for site
  shell: mkdir /home/"{{ user }}"/public_html/

- name: Setup Vhost in Apache
  shell: echo "<VirtualHost *:80>/n
    ServerName "{{ domain_name }}"/n
    ServerAlias www."{{ domain_name }}"/n 
    ServerAdmin webmaster@"{{ domain_name }}"/n
    DocumentRoot /home/"{{ user }}"/public_html /n 

    <Directory /home/"{{ user }}"/public_html>/n
        Options -Indexes +FollowSymLinks/n
        AllowOverride All/n
    </Directory>/n

    ErrorLog /var/log/httpd/"{{ domain_name }}"-error.log/n
    CustomLog /var/log/httpd/"{{ domain_name }}"-access.log combined/n
    </VirtualHost>" > /etc/httpd/conf.d/"{{ domain_name }}".conf/n

- name: Check syntax of httpd
  shell: httpd -t

- name: Restart httpd
  service:
    name: httpd
    state: restarted

  
