- name: Create Docroot for site
  shell: mkdir /home/"{{ user }}"/public_html/

- name: Create file
  file:
    path: /etc/httpd/conf.d/{{ domain_name }}.conf
    state: touch
    mode: '0644'

- name: Setup Vhost in Apache
  lineinfile:
    path: /etc/httpd/conf.d/{{ domain_name }}.conf
    state: present
    line: "{{ item }}"
  with_items:
  - <VirtualHost *:80>
  - ServerName {{ domain_name }}
  - ServerAlias www.{{ domain_name}}
  - ServerAdmin webmaster@{{ domain_name }}
  - DocumentRoot /home/{{ user }}/public_html
  - # space 
  - <Directory /home/{{ user }}/public_html>
  - Options -Indexes +FollowSymLinks
  - AllowOverride All
  - </Directory>
  - # space 
  - ErrorLog /var/log/httpd/{{ domain_name }}-error.log
  - CustomLog /var/log/httpd/{{ domain_name }}-access.log combined
  - </VirtualHost>

- name: Check syntax of httpd
  shell: httpd -t

- name: Restart httpd
  service:
    name: httpd
    state: restarted

  
