- hosts: all
  vars:
    machine:
      username: '{{ my_user }}'
      password: '{{ my password }}'

 # tasks:
 # - debug:
 #     var: machine
  

  
  name: Install LNMP
  remote_user: root

  roles:
    - httpd
    - php
    - mariadb
    
