- name: Login to server
  hosts: all
  vars:
    machine:
      username: '{{ my_user }}'
      password: '{{ my password }}'
  

- name: Install LNMP
  hosts: all
  remote_user: root

  roles:
    - httpd
    - php
    - mariadb
    
