- hosts: "{{ target }}"
  remote_user: root
  
  tasks:
  - name: Backup all Datababes /home/temp/mysql
    shell: mkdir /home/temp/mysql && cd /home/temp/mysql; echo "SHOW DATABASES;" | mysql -Bs| while read i ; do echo Dumping $i ; mysqldump --single-transaction $i |gzip -c > $i.sql.gz ; done

  - name: Stop MariaDB
    service:
      name: mariadb
      state: stopped

  - name: Backup SQL directory
    
    copy:
      src: /var/lib/mysql/
      dest: /var/lib/mysql.bak/
      owner: mysql
      group: mysql
      mode: '0755'
    
  - name: Remove MariaDB
    yum:
      name: "{{ packages }}"
    vars:
      packages:
      - maraidb
      - mariadb-server

  - name: Install MariaDB repo 10.3
    shell: curl -LsS https://r.mariadb.com/downloads/mariadb_repo_setup | sudo bash -s -- --mariadb-server-version="mariadb-10.3"

  - name: Install MariaDB 10.3
    yum:
      name: "{{ packages }}"
    vars:
      packages:
      - mariadb
      - mariadb-server
      - mariadb-client
      - mariadb-common

  - name: Start MariaDB
    service: 
      name: mariadb
      state: started

  - name: Run mysql_upgrade
    shell: mysql_upgrade
