- name: Start EC2 instance
  ec2:
    group_id: sg-02217564579113363
    instance_type: t2.micro
    image: ami-092b43193629811af
    wait: yes
    count: " {{ instances }}"
    vpc_subnet_id: subnet-03922064f9e389337
    assign_public_ip: yes
    keypair: Shane
    aws_region: us-east-2
    aws_access_key: "{{ access_key }}"
    aws_secret_key: "{{ secret_key }}"
    volumes:
      - device_name: /dev/xvda
        volume_type: gp2
        volume_size: "{{ disk }}"
