- name: Install PHP packages
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - php70
    - php70-php-mysqlnd
    - php70-php-fpm
    - php71
    - php71-php-mysqlnd
    - php71-php-fpm
    - php72
    - php72-php-mysqlnd
    - php72-php-fpm
    - php73
    - php73-php-mysqlnd
    - php73-php-fpm
    - php80
    - php80-php-mysqlnd
    - php80-php-fpm
    
- name: Copy script to remote server
  template:
    src: sed.sh
    dest: /home/scripts/

- name: Execute script
  shell: sh /home/scripts/sed.sh

- name: Start each PHP-FPM version
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - php70-php-fpm
    - php71-php-fpm
    - php72-php-fpm
    - php73-php-fpm
    - php74-php-fpm
    - php80-php-fpm

- name: Create wrappers for each PHP version
  template:
    src: wrapper.sh
    dest: /home/scripts/

- name: Execute script
  shell: sh /home/scripts/wrapper.sh

- name: Change permissions to 755
  shell: find /var/www/cgi-bin/php* -exec chmod 755 {} \;
  
- name: Remove php.conf
  file:
    path: /etc/httpd/conf.d/php.conf
    state: absent
  
- name:
  file:
    path: /etc/httpd/conf.d/php.conf
    state: touch
  
- name: Copy template to Apache
  template:
    src: php.conf
    dest: /etc/httpd/conf.d/php.conf

- name: Restart Services
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - httpd
    - php70-php-fpm
    - php71-php-fpm
    - php72-php-fpm
    - php73-php-fpm
    - php74-php-fpm
    - php80-php-fpm