- name: Wget CSF
  shell: cd /home/temp/ ; wget https://download.configserver.com/csf.tgz

- name: Extract tar CSF
  unarchive:
    src: /home/temp/csf.tgz
    dest: /home/temp/csf
  
- name: Install CSF
  shell: sh /home/temp/csf/install.sh

- name: Copy configuration template
  template:
    src: csf.conf
    dest: /etc/csf/csf.conf
    force: yes

- name: Start CSF & LFD
  shell: csf -ra